// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiapaaphtydefbxejtpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpYXBhYXBodHlkZWZieGVqdHBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTczNzUsImV4cCI6MjA2MjAzMzM3NX0.3W-JY-DkWk77RUOgU6JOjxNzm6jBhEuvEA3BmCEN1D8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);